export const changelog = [
  {
    version: '1.7',
    date: 'June 2026',
    changes: [
      'Difficulty ratings — vote 1 to 5 skulls on any spot, see the community average',
      'Filter the map and search results by Beginner, Intermediate, or Advanced difficulty',
      'Quick Add from Photo — create a spot directly from a camera roll photo, auto-filling location from GPS data when available',
      'Map now navigates to a new spot or event immediately after creation',
      'Browse the map and view spot previews without signing in',
      'Feedback board is viewable by everyone; posting and voting require an account',
    ],
  },
  {
    version: '1.6',
    date: 'June 2026',
    changes: [
      'Crews — create or join a crew to skate with your group',
      'Invite friends to crews and manage invites from the Crews menu',
      'Share spots directly to a crew',
      'Tap any crew member to open their profile',
      'Crew invite, join, and new-spot push notifications now open the right screen',
      'Tapping a notification clears its unread activity badge',
      'Rebranded deep links to inhabitants:// for invites and password reset',
    ],
  },
  {
    version: '1.5',
    date: 'May 2026',
    changes: [
      'Spot Passport — check in at spots and track every visit on your profile',
      'Check-ins appear in your friends feed with a 24hr same-spot cooldown',
      'Public Check-ins toggle in Settings to control your privacy',
      'Offline mode — spots load from cache when you lose signal',
      'Redesigned spot details with unified rating card and labeled action toolbar',
      "What's New popup shown once after each update",
    ],
  },
  {
    version: '1.4',
    date: 'May 2026',
    changes: [
      'Events — create skate sessions with date, time, and location',
      'Invite friends to private events or share publicly and with friends',
      'RSVP system with Going, Maybe, and Not Going responses',
      'Event details modal with attendee list visible to the creator',
      'Edit and cancel events after creation',
      'Map marker for custom event locations',
      'View linked spot details directly from an event',
      'Event invite push notifications with deep link to Invited tab',
      'Event reminders 24 hours and 1 hour before for Going RSVPs',
      'Unread badge on Events tab and hamburger menu for invites and RSVPs',
      'Event and RSVP notification toggles in Settings',
      'Content moderation on event title, description, and location',
      'Ambassador badge system — Local, Regular, and Ambassador tiers based on spot reviews',
      'Bookmark renamed from Save in spot details',
      'Saved tab label updated in Explore panel',
    ],
  },
  {
    version: '1.3',
    date: 'May 2026',
    changes: [
      'New SVG teardrop pin markers for all spot types',
      'Gray pins for your own spots, purple for friends, cream for strangers',
      'Green pins for skate parks, blue pins for skate shops',
      'Selected pins highlight in gold',
      'User search in Friends tab with friend indicator on results',
      'Closing a public profile returns to your profile modal',
      'Skate park and shop creation restricted to vetted accounts',
      'Splash screen background color matches animated splash',
      'Nearby buttons now equal height with consistent icon alignment',
      'Dark mode tinted icons in Explore panel and Create Spot modal',
      'Distance and location shown in spot details',
    ],
  },
  {
    version: '1.2',
    date: 'April 2026',
    changes: [
      'Add friends with send, accept, and cancel friend requests',
      'Bulk remove friends with long-press selection in Friends tab',
      'Spot visibility now supports Public, Friends, and Private',
      'Purple map markers for spots created by your friends',
      'Friends-only spots visible only to accepted friends',
      'Activity feed in Explore panel for reviews, saves, wishlists, flags, and conditions on your spots',
      'Friend social feed showing new spots and reviews from friends',
      'Notification badge on the menu for pending requests and unread activity',
      'Push notification when a friend request is accepted, deep links into the accepter profile',
      'Friend request notifications open your profile to accept or decline',
      'Notification preferences in Settings to opt out per event type',
      'Server side rate limiting plus client cooldown to prevent friend request spam',
      'Optional first and last name fields at signup and in profile edit',
      'Real time updates for friendships, spots, and activity without manual refresh',
      'Action sheet to switch spot visibility from the Mine tab',
    ],
  },
  {
    version: '1.1',
    date: 'April 2026',
    changes: [
      'Content moderation for hate speech',
      'Profile pictures with upload and moderation',
      'Avatar shown next to usernames in reviews and spot details',
      'Full profile page with stats, spots, and review history',
      'Skeleton loading for spot details',
      'Custom avatar map marker for your selected spots',
    ],
  },
  {
    version: '1.0',
    date: 'March 2026',
    changes: [
      'Custom skate park and skate shop markers',
      'Tag based spot search',
      'Photo uploads on spots',
      'Top rated spots nearby',
      'Share spots with friends',
      'Apple Maps and Google Maps directions',
      'Community flagging system',
      'Verified spot badges',
      'Vetted account editing for skate parks and shops',
      'Spot conditions reporting',
      'Push notifications for reviews, saves, and flags',
      'Dark mode support',
      'Password reset',
      'Wishlist and favorites',
    ],
  },
];
